### ISSUE TITLE
Compile ERRs

### ISSUE THREAD

**Issue by bologer** [angular/angular.io#1182]
I am trying to set-up 5 min. quickstart from this link - https://angular.io/docs/ts/latest/quickstart.html#!#app-folder. However, I have errors while running `nmp start`. 

Here is my `npm-debug.log` file: 
```
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\Programms\\nodejs\\node.exe',
1 verbose cli   'D:\\Programms\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'lite' ]
2 info using npm@3.6.0
3 info using node@v5.6.0
4 verbose run-script [ 'prelite', 'lite', 'postlite' ]
5 info lifecycle angular2-quickstart@1.0.0~prelite: angular2-quickstart@1.0.0
6 silly lifecycle angular2-quickstart@1.0.0~prelite: no script for prelite, continuing
7 info lifecycle angular2-quickstart@1.0.0~lite: angular2-quickstart@1.0.0
8 verbose lifecycle angular2-quickstart@1.0.0~lite: unsafe-perm in lifecycle true
9 verbose lifecycle angular2-quickstart@1.0.0~lite: PATH: D:\Programms\nodejs\node_modules\npm\bin\node-gyp-bin;D:\dev\angular\angular2-quickstart\node_modules\.bin;D:\Programms\nodejs\node_modules\npm\bin\node-gyp-bin;D:\dev\angular\angular2-quickstart\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;D:\Programms\Java\jdk1.8.0_65\bin;C:\Program Files (x86)\Skype\Phone\;D:\Programms\nodejs\;C:\Users\ateshabaev\AppData\Roaming\npm
10 verbose lifecycle angular2-quickstart@1.0.0~lite: CWD: D:\dev\angular\angular2-quickstart
11 silly lifecycle angular2-quickstart@1.0.0~lite: Args: [ '/d /s /c', 'lite-server' ]
12 silly lifecycle angular2-quickstart@1.0.0~lite: Returned: code: 1  signal: null
13 info lifecycle angular2-quickstart@1.0.0~lite: Failed to exec lite script
14 verbose stack Error: angular2-quickstart@1.0.0 lite: `lite-server`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (D:\Programms\nodejs\node_modules\npm\lib\utils\lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at EventEmitter.emit (events.js:185:7)
14 verbose stack     at ChildProcess.<anonymous> (D:\Programms\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at ChildProcess.emit (events.js:185:7)
14 verbose stack     at maybeClose (internal/child_process.js:827:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid angular2-quickstart@1.0.0
16 verbose cwd D:\dev\angular\angular2-quickstart
17 error Windows_NT 6.1.7601
18 error argv "D:\\Programms\\nodejs\\node.exe" "D:\\Programms\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "lite"
19 error node v5.6.0
20 error npm  v3.6.0
21 error code ELIFECYCLE
22 error angular2-quickstart@1.0.0 lite: `lite-server`
22 error Exit status 1
23 error Failed at the angular2-quickstart@1.0.0 lite script 'lite-server'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the angular2-quickstart package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     lite-server
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs angular2-quickstart
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls angular2-quickstart
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

The final structure of my application is the same as it was mention on this 5 min tut - https://angular.io/docs/ts/latest/quickstart.html#!#app-folder

**Comment by Foxandxss** [comment]
Be sure you `npm install`.

**Comment by bologer** [comment]
@Foxandxss, this did not solve the issue. 

npm_debug consists of the following lines: 
```
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\Programms\\nodejs\\node.exe',
1 verbose cli   'D:\\Programms\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.6.0
3 info using node@v5.6.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle angular2-quickstart@1.0.0~prestart: angular2-quickstart@1.0.0
6 silly lifecycle angular2-quickstart@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle angular2-quickstart@1.0.0~start: angular2-quickstart@1.0.0
8 verbose lifecycle angular2-quickstart@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle angular2-quickstart@1.0.0~start: PATH: D:\Programms\nodejs\node_modules\npm\bin\node-gyp-bin;D:\dev\angular\angular2-quickstart\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;D:\Programms\Java\jdk1.8.0_65\bin;C:\Program Files (x86)\Skype\Phone\;D:\Programms\nodejs\;C:\Users\ateshabaev\AppData\Roaming\npm
10 verbose lifecycle angular2-quickstart@1.0.0~start: CWD: D:\dev\angular\angular2-quickstart
11 silly lifecycle angular2-quickstart@1.0.0~start: Args: [ '/d /s /c',
11 silly lifecycle   'tsc && concurrently "npm run tsc:w" "npm run lite" ' ]
12 silly lifecycle angular2-quickstart@1.0.0~start: Returned: code: 2  signal: null
13 info lifecycle angular2-quickstart@1.0.0~start: Failed to exec start script
14 verbose stack Error: angular2-quickstart@1.0.0 start: `tsc && concurrently "npm run tsc:w" "npm run lite" `
14 verbose stack Exit status 2
14 verbose stack     at EventEmitter.<anonymous> (D:\Programms\nodejs\node_modules\npm\lib\utils\lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at EventEmitter.emit (events.js:185:7)
14 verbose stack     at ChildProcess.<anonymous> (D:\Programms\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at ChildProcess.emit (events.js:185:7)
14 verbose stack     at maybeClose (internal/child_process.js:827:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid angular2-quickstart@1.0.0
16 verbose cwd D:\dev\angular\angular2-quickstart
17 error Windows_NT 6.1.7601
18 error argv "D:\\Programms\\nodejs\\node.exe" "D:\\Programms\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v5.6.0
20 error npm  v3.6.0
21 error code ELIFECYCLE
22 error angular2-quickstart@1.0.0 start: `tsc && concurrently "npm run tsc:w" "npm run lite" `
22 error Exit status 2
23 error Failed at the angular2-quickstart@1.0.0 start script 'tsc && concurrently "npm run tsc:w" "npm run lite" '.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the angular2-quickstart package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     tsc && concurrently "npm run tsc:w" "npm run lite"
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs angular2-quickstart
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls angular2-quickstart
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```
