### ISSUE TITLE
gulp serve-and-sync shell.js: internal error

### ISSUE THREAD

**Issue by salorium** [angular/angular.io#1406]
```
salorium@ArchlinuxGeek ~/ng/angular.io (git)-[master] % gulp build-and-serve
(node:5910) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[19:28:33] Using gulpfile ~/ng/angular.io/gulpfile.js
[19:28:33] Starting '_shred-clean-devguide'...
[19:28:33] Starting '_shred-clean-devguide-shared-jade'...
[19:28:34] Starting '_shred-clean-api'...
[19:28:34] Starting 'build-dart-cheatsheet'...
shell.js: internal error
Error: ENOENT: no such file or directory, open '/tmp/shelljs_8f96edcc6e7f605223cb'
    at Error (native)
    at Object.fs.openSync (fs.js:634:18)
    at Object.fs.readFileSync (fs.js:502:33)
    at execSync (/home/salorium/ng/angular.io/node_modules/shelljs/src/exec.js:109:24)
    at Object._exec (/home/salorium/ng/angular.io/node_modules/shelljs/src/exec.js:214:12)
    at Object.exec (/home/salorium/ng/angular.io/node_modules/shelljs/src/common.js:182:23)
    at /home/salorium/ng/angular.io/node_modules/dgeni-packages/git/services/getPreviousVersions.js:18:28
    at versionInfo (/home/salorium/ng/angular.io/node_modules/dgeni-packages/git/services/versionInfo.js:133:22)
    at Array.invoke (/home/salorium/ng/angular.io/node_modules/di/lib/injector.js:75:15)
    at get (/home/salorium/ng/angular.io/node_modules/di/lib/injector.js:48:43)
    at /home/salorium/ng/angular.io/node_modules/di/lib/injector.js:71:14
    at Array.map (native)
    at Array.invoke (/home/salorium/ng/angular.io/node_modules/di/lib/injector.js:70:31)
    at get (/home/salorium/ng/angular.io/node_modules/di/lib/injector.js:48:43)
    at /home/salorium/ng/angular.io/node_modules/di/lib/injector.js:71:14
    at Array.map (native)
```

I have this error

**Comment by wardbell** [comment]
Not reproduceable nor is there enough guidance to research.  Closing this one. Please open a new issue when you have a repro with clear steps leading to the problem.

**Comment by pavlos256** [comment]
@salorium did you find a solution to this? I have the exact same problem on Arch.
