### ISSUE TITLE
Failed to instantiate module NG2_UPGRADE_0_

### ISSUE THREAD

**Issue by vance** [angular/angular.io#1496]
I tried to follow the angular.io upgrade docs. I get this error though:

```
index-dev.html:169 Error: Error: [$injector:modulerr] Failed to instantiate module NG2_UPGRADE_0_ due to:
	Error: [$injector:modulerr] Failed to instantiate module myApp due to:
	Error: [$injector:nomod] Module 'myApp' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
	http://errors.angularjs.org/1.4.10/$injector/nomod?p0=myApp
	    at http://127.0.0.1:9090/bower_components/angular/angular.js:68:12
	    at http://127.0.0.1:9090/bower_components/angular/angular.js:2012:17
	    at ensure (http://127.0.0.1:9090/bower_components/angular/angular.js:1936:38)
	    at module (http://127.0.0.1:9090/bower_components/angular/angular.js:2010:14)
	    at http://127.0.0.1:9090/bower_components/angular/angular.js:4472:22
	    at forEach (http://127.0.0.1:9090/bower_components/angular/angular.js:341:20)
	    at loadModules (http://127.0.0.1:9090/bower_components/angular/angular.js:4456:5)
	    at http://127.0.0.1:9090/bower_components/angular/angular.js:4473:40
	    at forEach (http://127.0.0.1:9090/bower_components/angular/angular.js:341:20)
	    at loadModules (http://127.0.0.1:9090/bower_components/angular/angular.js:4456:5)
	http://errors.angularjs.org/1.4.10/$injector/modulerr?p0=myApp&p1=Error%3A%…2F%2F127.0.0.1%3A9090%2Fbower_components%2Fangular%2Fangular.js%3A4456%3A5)
	    at http://127.0.0.1:9090/bower_components/angular/angular.js:68:12
	    at http://127.0.0.1:9090/bower_components/angular/angular.js:4495:15
	    at forEach (http://127.0.0.1:9090/bower_components/angular/angular.js:341:20)
	    at loadModules (http://127.0.0.1:9090/bower_components/angular/angular.js:4456:5)
	    at http://127.0.0.1:9090/bower_components/angular/angular.js:4473:40
	    at forEach (http://127.0.0.1:9090/bower_components/angular/angular.js:341:20)
	    at loadModules (http://127.0.0.1:9090/bower_components/angular/angular.js:4456:5)
	    at createInjector (http://127.0.0.1:9090/bower_components/angular/angular.js:4381:11)
	    at doBootstrap (http://127.0.0.1:9090/bower_components/angular/angular.js:1683:20)
	    at bootstrap (http://127.0.0.1:9090/bower_components/angular/angular.js:1704:12)
	http://errors.angularjs.org/1.4.10/$injector/modulerr?p0=NG2_UPGRADE_0_&p1=…F%2F127.0.0.1%3A9090%2Fbower_components%2Fangular%2Fangular.js%3A1704%3A12)
	    at http://127.0.0.1:9090/bower_components/angular/angular.js:68:12
	    at http://127.0.0.1:9090/bower_components/angular/angular.js:4495:15
	    at forEach (http://127.0.0.1:9090/bower_components/angular/angular.js:341:20)
	    at loadModules (http://127.0.0.1:9090/bower_components/angular/angular.js:4456:5)
	    at createInjector (http://127.0.0.1:9090/bower_components/angular/angular.js:4381:11)
	    at doBootstrap (http://127.0.0.1:9090/bower_components/angular/angular.js:1683:20)
	    at bootstrap (http://127.0.0.1:9090/bower_components/angular/angular.js:1704:12)
	    at eval (http://127.0.0.1:9090/node_modules/@angular/upgrade/upgrade.umd.js:878:38)
	    at ZoneDelegate.invoke (http://127.0.0.1:9090/node_modules/zone.js/dist/zone.js:323:29)
	    at Object.NgZoneImpl.inner.inner.fork.onInvoke (http://127.0.0.1:9090/node_modules/@angular/core/core.umd.js:6075:45)
	Evaluating http://127.0.0.1:9090/@main/@app/main.js
	Error loading http://127.0.0.1:9090/@main/@app/main.js
```
Below are the relevant files in my project. 
html:

```
<head>
   <!-- ... -->
    <!-- angular2 polyfills -->
    <script src="node_modules/es6-shim/es6-shim.min.js"></script>
    <script src="node_modules/zone.js/dist/zone.js"></script>
    <script src="node_modules/reflect-metadata/Reflect.js"></script>
    <script src="node_modules/systemjs/dist/system.src.js"></script>
    <!-- 2. Configure SystemJS -->
    <script src="systemjs.config.js"></script>
    <script>
        System.import('app').catch(function(err){ console.error(err); });
    </script>
</head>


<body  style="margin:0px;">

<my-app>
    <left-nav></left-nav>

    <div id="page-wrapper">

      <!-- main view -->
      <div ng-view style="min-width: 100%;">

    </div>

     <!-- <left-nav></left-nav> -->

    </div>
</my-app>

</body>

```

app.component.ts

```
import { Component, OnInit } from '@angular/core';
@Component({
    selector: 'my-app',
    directives:[],
    providers: [],
    template: `
        <h1> {{title}}</h1>        
      `,
    styles:[]
})
export class AppComponent implements OnInit{
    title = 'upgrade app';
    ngOnInit(){
        alert('inited');
    }
    constructor() { }
}

```

main.ts
```
import { bootstrap }    from '@angular/platform-browser-dynamic';
import {AppComponent} from './app.component';
import {upgradeAdapter } from './upgrade-adapter';

upgradeAdapter.bootstrap(document.body, ['myApp'], {strictDi: true});
```

upgrade-adapter.ts
```
import { UpgradeAdapter } from '@angular/upgrade';
export const upgradeAdapter = new UpgradeAdapter();
```
systemjs.config.js - I have my angular2 components inpath  `@main/@app` to differentiate it from angular1 components. 

```
/**
 * System configuration for Angular 2 apps
 * Adjust as necessary for your application needs.
 */
(function(global) {

	// map tells the System loader where to look for things
	var map = {
		'app':                        '@main/@app/', // 'dist',


		'@angular':                   'node_modules/@angular',
		'angular2-in-memory-web-api': 'node_modules/angular2-in-memory-web-api',
		'rxjs':                       'node_modules/rxjs'
	};

	// packages tells the System loader how to load when no filename and/or no extension
	var packages = {
		'app':                       { main: 'main.js',  defaultExtension: 'js' },
		'rxjs':                       { defaultExtension: 'js' },
		'angular2-in-memory-web-api': { defaultExtension: 'js' },
	};

	var ngPackageNames = [
		'common',
		'compiler',
		'core',
		'http',
		'platform-browser',
		'platform-browser-dynamic',
		'router',
		'router-deprecated',
		'upgrade',
	];

	// Add package entries for angular packages
	ngPackageNames.forEach(function(pkgName) {

		// Bundled (~40 requests):
		packages['@angular/'+pkgName] = { main: pkgName + '.umd.js', defaultExtension: 'js' };

		// Individual files (~300 requests):
		//packages['@angular/'+pkgName] = { main: 'index.js', defaultExtension: 'js' };
	});

	var config = {
		map: map,
		packages: packages
	}

	System.config(config);

})(this);
```

**Comment by 3du4** [comment]
I am facing exactly the same problem.
Would be very helpful if you could point here how you solved it.

**Comment by Foxandxss** [comment]
What's the status for this?

**Comment by 3du4** [comment]
@Foxandxss 

In my case I fixed by setting the correct path in ngPackageNames (systemjs.config.js)  

`  var ngPackageNames = [
    '@angular/common',
    '@angular/compiler',
    '@angular/core',
    '@angular/http',
    '@angular/platform-browser',
    '@angular/platform-browser-dynamic',
    '@angular/router',
    '@angular/testing',
    '@angular/upgrade'
  ];`
