### ISSUE TITLE
Can't run locally 

### ISSUE THREAD

**Issue by sleekvick** [angular/angular.io#1653]
everytime i run this command "gulp serve-and-sync" I get the error below.

angular.io/node_modules/jsdom/lib/jsdom.js:3
() => `jsdom 7.x onward only works on Node.js 4 or newer: https://github.com/t
 ^
SyntaxError: Unexpected token )

Am trying to run the documentation locally, i have installed node v.4 and the latest version of io.js
Please help

**Comment by Foxandxss** [comment]
What node v4 are you using? Could you try latest 4.x?

**Comment by sleekvick** [comment]
I ran node -v
version == v1.8.4

**Comment by Foxandxss** [comment]
That is really really really old.

**Comment by sleekvick** [comment]
But i've downloaded the latest version of node and re-installed...also did the 
brew update 
brew update node 
and restarted the terminal 

so i assumed node already got updated!!

what can i do?

**Comment by Foxandxss** [comment]
Don't use brew for node. Use `nvm`. Much much better.

**Comment by sleekvick** [comment]
Ok so i've been to get the latest node...but after running 
gulp serve-and-sync

it's still doesn't open up the browser with the http://localhost:3000 address 
although is those this :

[23:26:20] Using gulpfile ~/Documents/angular.io/gulpfile.js
[23:26:20] Starting '_shred-clean-devguide'...
[23:26:20] Starting '_copy-example-boilerplate'...
[23:26:20] Copying example boilerplate files
[23:26:25] Starting '_shred-clean-devguide-shared-jade'...
[23:26:33] Starting '_shred-clean-api'...
[23:26:33] Starting 'build-dart-cheatsheet'...
[23:26:33] 'build-dart-cheatsheet' errored after 396 μs
[23:26:33] Error: API related tasks require the angular2 repo to be at /Users/Sleekvick/Documents/angular
    at checkAngularProjectPath (/Users/Sleekvick/Documents/angular.io/gulpfile.js:1195:11)
    at buildApiDocs (/Users/Sleekvick/Documents/angular.io/gulpfile.js:991:3)
    at Gulp.<anonymous> (/Users/Sleekvick/Documents/angular.io/gulpfile.js:500:10)
    at module.exports (/Users/Sleekvick/Documents/angular.io/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/Sleekvick/Documents/angular.io/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/Sleekvick/Documents/angular.io/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/Sleekvick/Documents/angular.io/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at /usr/local/lib/node_modules/gulp/bin/gulp.js:129:20
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
[23:26:33] Finished '_shred-clean-devguide-shared-jade' after 7.5 s
[23:26:33] Finished '_shred-clean-devguide' after 13 s
[23:26:33] Finished '_shred-clean-api' after 33 ms
[23:26:33] Finished '_copy-example-boilerplate' after 13 s

**Comment by Foxandxss** [comment]
For that particular command you need the angular repo alongside this repo. Check the README For other commands that doesn't need that.

**Comment by sleekvick** [comment]
None of the commands have been able to launch the documentation on my browser...

I need this documentation to work offline because i don't have access to internet all the time.
Thanks.

**Comment by Foxandxss** [comment]
`gulp serve-and-sync-devguide` should work for you.

**Comment by sleekvick** [comment]
Thanks
I had to run this command  npm rebuild node-sass
before it worked.

**Comment by Foxandxss** [comment]
Nice. I am closing this.
