### ISSUE TITLE
Upgrade adapter failed to load AMD module extending Array.prototype

### ISSUE THREAD

**Issue by ptomaszi** [angular/angular.io#1764]
My application is running in mixed mode using upgrade adapter provided by Angular team. I have the following AMD module defined:
```
define(function () {
    'use strict';

    Array.prototype.pushArray = pushArray;
    Array.prototype.clear = clear;
    Array.prototype.fill = fill;
    
    return;

    function pushArray() {
        this.push.apply(this, this.concat.apply([], arguments));
    }

    function clear() {
        this.length = 0;
    }

    function fill() {
        this.clear();
        this.pushArray.apply(this, arguments);
    }
});
```

When I load that using SystemJS module loader I got the following exception:

Unhandled Promise rejection: Error: Cannot resolve all parameters for 'Console'(?). Make sure that all the parameters are decorated with Inject or have valid type annotations and that 'Console' is decorated with Injectable.
	    at NoAnnotationError.BaseException [as constructor] (http://localhost:4200/vendor/@angular/core/src/facade/exceptions.js:17:23)
	    at new NoAnnotationError (http://localhost:4200/vendor/@angular/core/src/di/reflective_exceptions.js:217:16)
	    at _dependenciesFor (http://localhost:4200/vendor/@angular/core/src/di/reflective_provider.js:182:15)
	    at resolveReflectiveFactory (http://localhost:4200/vendor/@angular/core/src/di/reflective_provider.js:72:24)
	    at resolveReflectiveProvider (http://localhost:4200/vendor/@angular/core/src/di/reflective_provider.js:96:97)
	    at Array.map (native)
	    at Object.resolveReflectiveProviders (http://localhost:4200/vendor/@angular/core/src/di/reflective_provider.js:104:31)
	    at Function.ReflectiveInjector.resolve (http://localhost:4200/vendor/@angular/core/src/di/reflective_injector.js:357:38)
	    at Function.ReflectiveInjector.resolveAndCreate (http://localhost:4200/vendor/@angular/core/src/di/reflective_injector.js:387:62)
	    at Object.browserPlatform (http://localhost:4200/vendor/@angular/platform-browser/src/platform_browser.js:38:57)
	Evaluating http://localhost:4200/main.js
	Error loading http://localhost:4200/main.js ; Zone: <root> ; Task: Promise.then ; Value: Error: Error: Cannot resolve all parameters for 'Console'(?). Make sure that all the parameters are decorated with Inject or have valid type annotations and that 'Console' is decorated with Injectable.(…)

I have tried to debug the code and it looks like the error is comming from the following module:

resolvedDeps = _dependenciesFor(useClass); //useClass = function Console()

function _dependenciesFor(typeOrFunc: any): ReflectiveDependency[] {
  var params = reflector.parameters(typeOrFunc);
  if (isBlank(params)) return [];
  if (params.some(isBlank)) {
    **throw new NoAnnotationError(typeOrFunc, params);**
  }
  return params.map((p: any[]) => _extractToken(typeOrFunc, p, params));
}

reflective_provider.ts - resolveReflectiveFactory
reflective_provider.ts - resolveReflectiveProvider
reflective_providers.ts - resolveReflectiveProviders
reflective_injector.ts - ReflectiveInjector.resolve
reflective_injector.ts - ReflectiveInjector.resolveAndCreate
platform_browser.ts - browsePlatform
upgrade_adapter.ts - UpgradeAdapter.bootstrap

**Comment by Foxandxss** [comment]
Sorry sir, this is not a support forum.

Is better for you to go to stackoverflow for that.

Thanks!
