### ISSUE TITLE
chore (gulp): SyntaxError: Unexpected token ...

### ISSUE THREAD

**Issue by bampakoa** [angular/angular.io#1921]
I am trying to execute `gulp serve-and-sync` and I get the following error:

```
C:\Users\abampakos\Documents\GitHub\angular.io\gulpfile.js:514
      spawnInfo = spawnExt('npm', ['install', ...sources], {cwd: EXAMPLES_PATH});
                                              ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Liftoff.handleArguments (C:\Users\abampakos\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:116:3)
    at Liftoff.<anonymous> (C:\Users\abampakos\AppData\Roaming\npm\node_modules\gulp\node_modules\liftoff\index.js:193:16)
    at module.exports (C:\Users\abampakos\AppData\Roaming\npm\node_modules\gulp\node_modules\liftoff\node_modules\flagged-respawn\index.js:17:3)

```

**Comment by Foxandxss** [comment]
We broke Node 4 support with that commit.

/cc @wardbell

**Comment by bampakoa** [comment]
closing as of #1982
