### ISSUE TITLE
TS API Doc gen failing: `CompilerOptions` used as const and type name

### ISSUE THREAD

**Issue by chalin** [angular/angular.io#2023]
In TS the compiler name space for type names seems to be independent of that of other syntactic entities. E.g., currently (https://github.com/angular/angular/commit/91c64d2b8d898faff437cd60bc22560c381ee45f) in `angular/modules/@angular/core/src/linker/compiler.ts`, the **same identifier** is used in **two declarations**:
```typescript
export type CompilerOptions = { … }
…
export const CompilerOptions = new OpaqueToken('compilerOptions');
```
The tsc is perfectly happy with this (and this idiom is used throughout the angular code). But, this breaks the API doc generation:
```
error:   TypeError: Cannot read property 'pos' of undefined
    at getText (/Users/chalin/git/angular.io/node_modules/dgeni-packages/typescript/processors/readTypeScriptModules.js:432:42)
    at /Users/chalin/git/angular.io/node_modules/dgeni-packages/typescript/processors/readTypeScriptModules.js:190:26
    at Array.forEach (native)
...
```
because it tries to get the type alias definition from the const declaration.

cc @petebacondarwin @ericjim @wardbell @brandonroberts

**Comment by chalin** [comment]
FYI: a source side fix might be on its way into Angular: https://github.com/angular/angular/pull/10457.

**Comment by chalin** [comment]
Solved via https://github.com/angular/angular/pull/10457.
