### ISSUE TITLE
Error trying to run the sample

### ISSUE THREAD

**Issue by graphicsxp** [angular/angular.io#2485]
I get this error. What is '...sources'  ?   Should I replace that with something in the gulp file ? 

```
c:\dev\angular.io-master\gulpfile.js:580                                                                                                                                                     
      spawnInfo = spawnExt('npm', ['install', ...sources], {cwd: EXAMPLES_PATH});                                                                                                            
                                              ^^^                                                                                                                                            
  ```
```
                                                                                                                                                                                           
SyntaxError: Unexpected token ...                                                                                                                                                            
    at exports.runInThisContext (vm.js:53:16)                                                                                                                                                
    at Module._compile (module.js:373:25)                                                                                                                                                    
    at Object.Module._extensions..js (module.js:416:10)                                                                                                                                      
    at Module.load (module.js:343:32)                                                                                                                                                        
    at Function.Module._load (module.js:300:12)                                                                                                                                              
    at Module.require (module.js:353:17)                                                                                                                                                     
    at require (internal/module.js:12:17)                                                                                                                                                    
    at Liftoff.handleArguments (C:\Users\berthsa\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:116:3)                                                                                    
    at Liftoff.<anonymous> (C:\Users\berthsa\AppData\Roaming\npm\node_modules\gulp\node_modules\liftoff\index.js:198:16)                                                                     
    at module.exports (C:\Users\berthsa\AppData\Roaming\npm\node_modules\gulp\node_modules\liftoff\node_modules\flagged-respawn\index.js:17:3)         
```

**Comment by mattdistefano** [comment]
What version of node are you running?

**Comment by graphicsxp** [comment]
Matt, I'm using Node v. 4.5.0

**Comment by mattdistefano** [comment]
See https://github.com/angular/angular.io#development-setup - looks like you need 5 or above.

**Comment by mattdistefano** [comment]
Also - the `...` is an [array spread operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_operator). It's a newer feature of the language, so older versions of node either don't support it or require a special runtime flag to enable support.

**Comment by Foxandxss** [comment]
you need node v5+
