### ISSUE TITLE
Live-example resource issue in IE11 in Architecture Overview doc

### ISSUE THREAD

**Issue by DarkChocoholicDev** [angular/angular.io#2693]
In the Architecture Overview sections of the Guide docs, there is a line that says:

> The code referenced on this page is available as a .

The HTML for that line is this:

```
<p>
  The code referenced on this page is available as a
  <live-example class="ng-scope"></live-example>
  .
</p>
```
Upon loading the page, the console log shows the following error:

```
TypeError: Object doesn't support property or method 'includes':
   at NgIoUtil.isDoc (https://angular.io/resources/js/util.js:9:9)
   at compile (https://angular.io/resources/js/directives/live-example.js:58:7)
   at Z (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js:65:271)
   at O (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js:55:224)
   at O (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js:55:311)
   at O (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js:55:311)
   at O (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js:55:311)
   at O (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js:55:311)
   at O (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js:55:311)
   at K (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js:53:224) <live-example>
```

Repro environment:

- Windows 10 Pro, 64-bit
- IE 11, version 11.321.14393.0

It does not repro with Edge.

-- Keith

**Comment by wardbell** [comment]
I just now tried in IE 11 (same build) on Windows 10 Pro 64bit ... and no problem. Sounds like a flake to me. I'm going to have to close this issue.

**Comment by DarkChocoholicDev** [comment]
> Sounds like a flake (not you, the experience you had) to me.

You can call me a flake if you want--just don't call me a _fluke_. :-)

But nay, this was no fluke! On closer inspection, it appears that NgIoUtil is assuming that the JavaScript String implementation has an "includes" function. On IE, that appears to not be the case, and is documented as such on Mozilla. (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/includes#Browser_compatibility)

I confirmed that both my desktop and Surface Pro (both running Windows 10) exhibit the failure when viewing the Angular 2 docs. Is there, perhaps, a polyfill that's expected to get loaded, that may be getting loaded on your system but not mine? Or maybe your system is picking up a different (cached?) util.js that doesn't use String.includes? On my system, IE's developer tools displays it as this:

```
// This will be nicer once we switch to Ng2. For now, define a singleton.

var NgIoUtil = (function () {

    function NgIoUtil() { }

    NgIoUtil.isDoc = function ($location, lang) {
        var loc = $location.absUrl();
        return loc.includes('/docs/' + lang + '/');
    };
```

How about re-opening this, and I'll help you with a repro or remote diagnosis?

-- Keith
