### ISSUE TITLE
"Routing & Navigation" plunker throws exceptions

### ISSUE THREAD

**Issue by dtgriscom** [angular/angular.io#2779]
The document page "Routing & Navigation" at https://angular.io/docs/ts/latest/guide/router.html references a demo Plunkr that throws exceptions when used in specific ways (confirmed with Chrome 52.0.2743.82 (64-bit) under OS X 10.10.5; also confirmed with Firefox 38.0.1 under Windows XP). To replicate:

1. Open the demo Plunkr at https://angular.io/resources/live-examples/router/ts/plnkr.html
2. Wait until the Plunkr is loaded and running (you'll see "Angular Router", with the "Heroes" tab selected)
3. Open the JavaScript console
4. Click the "Crisis Center" tab; the Crisis Center will open (good)
5. Click one of the Crises (e.g. "Dragon Burning Cities"): the crisis will open (good)
6. Click one of the "Heroes", "Admin" or "Login" tabs: nothing changes (bad) and the console will show lots of exceptions (bad). Initial exception is:

`core.umd.js:3004 EXCEPTION: Uncaught (in promise): TypeError: Cannot read property 'canDeactivate' of null`

7. Click others of the "Heroes"/"Admin"/"Login" tabs: nothing will change (bad), and no further exceptions will appear (good)
8. Click "Cancel" under the crisis: the crisis will disappear (good)
9. Click others of the "Heroes"/"Admin"/"Login" tabs: the display will switch to that tab (good).

Guess: there's either a bug in the guards for the demo code, or the demo exposes a bug in Angular 2's routing code; I'm not far enough up the learning curve to figure out which.

Full JavaScript console output:

    URL visited /?p=preview
    TypeScript transpiling to CommonJS, consider setting module: "system" in typescriptOptions to transpile directly to System.register format
    Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.
    Preloaded: crisis-center
    EXCEPTION: Uncaught (in promise): TypeError: Cannot read property 'canDeactivate' of null
    ORIGINAL STACKTRACE:
    Error: Uncaught (in promise): TypeError: Cannot read property 'canDeactivate' of null
        at resolvePromise (zone.js@0.6.25?main=browser:429)
        at zone.js@0.6.25?main=browser:406
        at ZoneDelegate.invoke (zone.js@0.6.25?main=browser:203)
        at Object.onInvoke (core.umd.js:6206)
        at ZoneDelegate.invoke (zone.js@0.6.25?main=browser:202)
        at Zone.run (zone.js@0.6.25?main=browser:96)
        at zone.js@0.6.25?main=browser:462
        at ZoneDelegate.invokeTask (zone.js@0.6.25?main=browser:236)
        at Object.onInvokeTask (core.umd.js:6197)
        at ZoneDelegate.invokeTask (zone.js@0.6.25?main=browser:235)
    Unhandled Promise rejection: Cannot read property 'canDeactivate' of null ; Zone: angular ; Task: Promise.then ; Value: TypeError: Cannot read property 'canDeactivate' of null(…) TypeError: Cannot read property 'canDeactivate' of null
        at CanDeactivateGuard.canDeactivate (http://run.plnkr.co/4sGfJSJijYInwiRy/app/can-deactivate-guard.service.ts!transpiled:16:25)
        at MapSubscriber.eval [as project] (https://unpkg.com/@angular/router/bundles/router.umd.js:2855:53)
        at MapSubscriber._next (https://unpkg.com/rxjs/operator/map.js:77:35)
        at MapSubscriber.Subscriber.next (https://unpkg.com/rxjs/Subscriber.js:89:18)
        at ArrayObservable._subscribe (https://unpkg.com/rxjs/observable/ArrayObservable.js:114:28)
        at ArrayObservable.Observable.subscribe (https://unpkg.com/rxjs/Observable.js:45:27)
        at Observable._subscribe (https://unpkg.com/rxjs/Observable.js:103:28)
        at MapOperator.call (https://unpkg.com/rxjs/operator/map.js:54:23)
        at Observable.subscribe (https://unpkg.com/rxjs/Observable.js:42:22)
        at Observable._subscribe (https://unpkg.com/rxjs/Observable.js:103:28)
    Error: Uncaught (in promise): TypeError: Cannot read property 'canDeactivate' of null(…)

**Comment by Foxandxss** [comment]
I confirm the issue. @brandonroberts can you take a look please? It probably need fixing in the code, prose and e2e.

**Comment by brandonroberts** [comment]
This is a bug in the router that has been fixed. See https://github.com/angular/angular/issues/12592.

**Comment by brandonroberts** [comment]
Closing as its resolved in router version `3.2.x`
