### ISSUE TITLE
EventEmitter giving issue after migrating to AOT

### ISSUE THREAD

**Issue by vasuneet** [angular/angular.io#3019]
Hi ,

I migrated to Angular AOT and followed all steps. I am able to run my application with AOT. But the non-aot version of my application worked stop after that and giving me the following issue after that : 

	Error: Can't resolve all parameters for EventEmitter: (?).
	    at CompileMetadataResolver._getDependenciesMetadata (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:12564:21)
	    at CompileMetadataResolver._getTypeMetadata (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:12458:28)
	    at eval (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:12608:43)
	    at Array.forEach (native)
	    at CompileMetadataResolver._getProvidersMetadata (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:12588:21)
	    at CompileMetadataResolver.getNonNormalizedDirectiveMetadata (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:12184:32)
	    at CompileMetadataResolver._loadDirectiveMetadata (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:12075:44)
	    at eval (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:12341:89)
	    at eval (http://localhost:3000/node_modules/@angular/compiler/bundles/compiler.umd.js:12256:101)
	    at Array.map (native)

**Comment by vasuneet** [comment]
Any update on this ?

**Comment by Foxandxss** [comment]
This is not the right place to ask, sorry.

This issue tracker is only for documentation issues.

It is better to ask at stackoverflow.

Thank you.

**Comment by vasuneet** [comment]
That's fine then let me know where is in documentation you have mentioned to run running aot and non-aot version simultaneously.

**Comment by Foxandxss** [comment]
That is a different issue altogether.

**Comment by vasuneet** [comment]
No this is coming in this case only. Otherwise non-aot was worknig fine.
