### ISSUE TITLE
gulp serve-and-sync results in "TypeError: Cannot read property 'description' of undefined"

### ISSUE THREAD

**Issue by ctrom** [angular/angular.io#3366]
When trying to run the `gulp serve-and-sync` command, I encounter the following error:

```
error:   TypeError: Cannot read property 'description' of undefined
    at /home/christopher/Projects/angular/angular.io/tools/api-builder/angular.io-package/processors/addJadeDataDocsProcessor.js:142:51
    at arrayMap (/home/christopher/Projects/angular/angular.io/node_modules/lodash/lodash.js:660:23)
    at Function.map (/home/christopher/Projects/angular/angular.io/node_modules/lodash/lodash.js:9571:14)
    at interceptor (/home/christopher/Projects/angular/angular.io/node_modules/lodash/lodash.js:16970:35)
    at thru (/home/christopher/Projects/angular/angular.io/node_modules/lodash/lodash.js:8812:14)
    at /home/christopher/Projects/angular/angular.io/node_modules/lodash/lodash.js:4379:28
    at arrayReduce (/home/christopher/Projects/angular/angular.io/node_modules/lodash/lodash.js:704:21)
    at baseWrapperValue (/home/christopher/Projects/angular/angular.io/node_modules/lodash/lodash.js:4378:14)
    at LazyWrapper.lazyValue [as value] (/home/christopher/Projects/angular/angular.io/node_modules/lodash/lodash.js:1880:16)
    at baseWrapperValue (/home/christopher/Projects/angular/angular.io/node_modules/lodash/lodash.js:4376:25)
    at LodashWrapper.wrapperValue (/home/christopher/Projects/angular/angular.io/node_modules/lodash/lodash.js:9067:14)
    at /home/christopher/Projects/angular/angular.io/tools/api-builder/angular.io-package/processors/addJadeDataDocsProcessor.js:170:12
    at arrayEach (/home/christopher/Projects/angular/angular.io/node_modules/lodash/lodash.js:537:11)
    at Function.forEach (/home/christopher/Projects/angular/angular.io/node_modules/lodash/lodash.js:9359:14)
    at Object.$process (/home/christopher/Projects/angular/angular.io/tools/api-builder/angular.io-package/processors/addJadeDataDocsProcessor.js:114:9)
    at /home/christopher/Projects/angular/angular.io/node_modules/dgeni/lib/Dgeni.js:179:54

```

This is after following the instructions in the [Development Setup](https://github.com/angular/angular.io#development-setup) guide.
Node version: v6.2.0
npm version: 4.4.1

**Comment by ctrom** [comment]
I'm not experiencing this issue with the latest code revisions.
