### ISSUE TITLE
Missing angular2 repo while running serve-and-sync

### ISSUE THREAD

**Issue by filipesilva** [angular/angular.io#342]
Trying to run the `serve-and-sync` task after the steps in `Development Setup` outputs the following error:

```
[14:49:58] Error: build-api-docs task requires the angular2 repo to be at E:/sandbox/angular
    at Gulp.<anonymous> (E:\sandbox\angular.io\gulpfile.js:102:11)
    at module.exports (E:\sandbox\angular.io\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (E:\sandbox\angular.io\node_modules\gulp\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (E:\sandbox\angular.io\node_modules\gulp\node_modules\orchestrator\index.js:214:10)
    at E:\sandbox\angular.io\node_modules\gulp\node_modules\orchestrator\index.js:279:18
    at finish (E:\sandbox\angular.io\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:21:8)
    at E:\sandbox\angular.io\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:43:4
    at _fulfilled (E:\sandbox\angular.io\node_modules\dgeni\node_modules\q\q.js:798:54)
    at self.promiseDispatch.done (E:\sandbox\angular.io\node_modules\dgeni\node_modules\q\q.js:827:30)
    at Promise.promise.promiseDispatch (E:\sandbox\angular.io\node_modules\dgeni\node_modules\q\q.js:760:13)
```

Cloning https://github.com/angular/angular one level above solves this, but it is not documented in the readme.

**Comment by wardbell** [comment]
My bad in my instructions. 

That gulp task rebuilds everything ... including the API docs which require access to the angular2 source code repo. The task assumes/requires that a clone of that repo reside under that name in a sibling folder to your angular.io clone.

You don't have to clone one level above (which would bring down a ton of irrelevant stuff). Just clone angular into a neighboring folder once and carry on.

Don't have a better way right now. Welcome suggestions.

**Comment by filipesilva** [comment]
Ah that is what I meant, a sibling directory. I should have been more clear. In the PR, I word it as `Clone this repo and [angular](https://github.com/angular/angular) on the same parent directory`.

**Comment by wardbell** [comment]
Don't sweat it. I didn't mean just that. I think the whole doc could be more clear. But it is mostly for us so I'm not worrying about it.
