### ISSUE TITLE
running gulp serve-and-sync outputs cheatsheetItem error

### ISSUE THREAD

**Issue by filipesilva** [angular/angular.io#476]
Seems to be some invalid syntax. `gulp serve-and-sync-devguide` is unnaffected.

Will investigate.

```
$ gulp serve-and-sync
[12:41:26] Using gulpfile E:\dev\ideablade\angular.io\gulpfile.js
[12:41:26] Starting '_shred-clean-devguide'...
[12:41:26] Starting '_shred-clean-api'...
[12:41:26] Starting 'build-dart-cheatsheet'...
[12:41:29] Starting 'build-plunkers'...
[12:41:30] Finished 'build-plunkers' after 801 ms
[12:41:30] Starting '_zip-examples'...
[12:41:30] Finished '_zip-examples' after 55 ms
info:    running processor: readFilesProcessor
info:    running processor: extractJSDocCommentsProcessor
info:    running processor: parseTagsProcessor
info:    running processor: extractTagsProcessor
error:   Error: "@cheatsheetItem" tag has an invalid format - item must start with one of the following field specifiers:
syntax:
description:
but instead it contained: "`bootstrap​(MyAppComponent, [MyService, provide(...)]);`
Bootstraps an application with MyAppComponent as the root component and configures the DI providers.
" - doc "Bootstrapping" (cheatsheet-section)  - from file "cheatsheet/bootstrapping.md" - starting at line 1
    at transforms (E:\dev\ideablade\angular.io\tools\api-builder\cheatsheet-package\tag-defs\cheatsheet-item.js:10:15)
    at Object.tagDef.getProperty (E:\dev\ideablade\angular.io\node_modules\dgeni-packages\jsdoc\processors\extract-tags.js:54:17)
    at E:\dev\ideablade\angular.io\node_modules\dgeni-packages\jsdoc\processors\extract-tags.js:122:38
    at Function.forEach (E:\dev\ideablade\angular.io\node_modules\dgeni-packages\node_modules\lodash\dist\lodash.js:3298:15)
    at readTags (E:\dev\ideablade\angular.io\node_modules\dgeni-packages\jsdoc\processors\extract-tags.js:120:9)
    at E:\dev\ideablade\angular.io\node_modules\dgeni-packages\jsdoc\processors\extract-tags.js:86:11
    at Function.forEach (E:\dev\ideablade\angular.io\node_modules\dgeni-packages\node_modules\lodash\dist\lodash.js:3298:15)
    at tagExtractor (E:\dev\ideablade\angular.io\node_modules\dgeni-packages\jsdoc\processors\extract-tags.js:65:9)
    at E:\dev\ideablade\angular.io\node_modules\dgeni-packages\jsdoc\processors\extract-tags.js:20:9
    at Array.forEach (native)
error:   Error processing docs:
[12:41:30] 'build-dart-cheatsheet' errored after 3.66 s
[12:41:30] Error: "@cheatsheetItem" tag has an invalid format - item must start with one of the following field specifiers:
syntax:
description:
but instead it contained: "`bootstrap​(MyAppComponent, [MyService, provide(...)]);`
Bootstraps an application with MyAppComponent as the root component and configures the DI providers.
" - doc "Bootstrapping" (cheatsheet-section)  - from file "cheatsheet/bootstrapping.md" - starting at line 1
    at transforms (E:\dev\ideablade\angular.io\tools\api-builder\cheatsheet-package\tag-defs\cheatsheet-item.js:10:15)
    at Object.tagDef.getProperty (E:\dev\ideablade\angular.io\node_modules\dgeni-packages\jsdoc\processors\extract-tags.js:54:17)
    at E:\dev\ideablade\angular.io\node_modules\dgeni-packages\jsdoc\processors\extract-tags.js:122:38
    at Function.forEach (E:\dev\ideablade\angular.io\node_modules\dgeni-packages\node_modules\lodash\dist\lodash.js:3298:15)
    at readTags (E:\dev\ideablade\angular.io\node_modules\dgeni-packages\jsdoc\processors\extract-tags.js:120:9)
    at E:\dev\ideablade\angular.io\node_modules\dgeni-packages\jsdoc\processors\extract-tags.js:86:11
    at Function.forEach (E:\dev\ideablade\angular.io\node_modules\dgeni-packages\node_modules\lodash\dist\lodash.js:3298:15)
    at tagExtractor (E:\dev\ideablade\angular.io\node_modules\dgeni-packages\jsdoc\processors\extract-tags.js:65:9)
    at E:\dev\ideablade\angular.io\node_modules\dgeni-packages\jsdoc\processors\extract-tags.js:20:9
    at Array.forEach (native)
[12:41:30] Finished '_shred-clean-api' after 3.7 s
[12:41:30] Finished '_shred-clean-devguide' after 3.72 s
zip created: public/resources/zips/styleguide.jsonly.zip (1921 total bytes)
zip created: public/resources/zips/styleguide.zip (3914 total bytes)
```

**Comment by filipesilva** [comment]
Hm, the above error was due to me simply not having an updated version of `angular/angular`. But after updating I get a similar one:

```
$ gulp serve-and-sync
[12:55:58] Using gulpfile E:\dev\ideablade\angular.io\gulpfile.js
[12:55:58] Starting '_shred-clean-devguide'...
[12:55:58] Starting '_shred-clean-api'...
[12:55:58] Starting 'build-dart-cheatsheet'...
[12:56:00] Starting 'build-plunkers'...
[12:56:01] Finished 'build-plunkers' after 677 ms
[12:56:01] Starting '_zip-examples'...
[12:56:01] Finished '_zip-examples' after 58 ms
info:    running processor: readFilesProcessor
info:    running processor: extractJSDocCommentsProcessor
info:    running processor: parseTagsProcessor
info:    running processor: extractTagsProcessor
error:   Error: "@cheatsheetItem" tag has an invalid format - item must start with one of the following field specifiers:
syntax:
description:
but instead it contained: "`<a [routerLink]="[ '/MyCmp', {myParam: 'value' } ]">`|`[routerLink]`
description:
Creates a link to a different view based on a route instruction consisting of a route name and optional parameters. The route name matches the as property of a configured route. Add the '/' prefix to navigate to a root route; add the './' prefix for a child route.

" - doc "Routing and navigation" (cheatsheet-section)  - from file "cheatsheet/routing.md" - starting at line 1
    at transforms (E:\dev\ideablade\angular.io\tools\api-builder\cheatsheet-package\tag-defs\cheatsheet-item.js:10:15)
    at Object.tagDef.getProperty (E:\dev\ideablade\angular.io\node_modules\dgeni-packages\jsdoc\processors\extract-tags.js:54:17)
    at E:\dev\ideablade\angular.io\node_modules\dgeni-packages\jsdoc\processors\extract-tags.js:122:38
    at Function.forEach (E:\dev\ideablade\angular.io\node_modules\dgeni-packages\node_modules\lodash\dist\lodash.js:3298:15)
    at readTags (E:\dev\ideablade\angular.io\node_modules\dgeni-packages\jsdoc\processors\extract-tags.js:120:9)
    at E:\dev\ideablade\angular.io\node_modules\dgeni-packages\jsdoc\processors\extract-tags.js:86:11
    at Function.forEach (E:\dev\ideablade\angular.io\node_modules\dgeni-packages\node_modules\lodash\dist\lodash.js:3298:15)
    at tagExtractor (E:\dev\ideablade\angular.io\node_modules\dgeni-packages\jsdoc\processors\extract-tags.js:65:9)
    at E:\dev\ideablade\angular.io\node_modules\dgeni-packages\jsdoc\processors\extract-tags.js:20:9
    at Array.forEach (native)
error:   Error processing docs:
[12:56:01] 'build-dart-cheatsheet' errored after 3.6 s
[12:56:01] Error: "@cheatsheetItem" tag has an invalid format - item must start with one of the following field specifiers:
syntax:
description:
but instead it contained: "`<a [routerLink]="[ '/MyCmp', {myParam: 'value' } ]">`|`[routerLink]`
description:
Creates a link to a different view based on a route instruction consisting of a route name and optional parameters. The route name matches the as property of a configured route. Add the '/' prefix to navigate to a root route; add the './' prefix for a child route.

" - doc "Routing and navigation" (cheatsheet-section)  - from file "cheatsheet/routing.md" - starting at line 1
    at transforms (E:\dev\ideablade\angular.io\tools\api-builder\cheatsheet-package\tag-defs\cheatsheet-item.js:10:15)
    at Object.tagDef.getProperty (E:\dev\ideablade\angular.io\node_modules\dgeni-packages\jsdoc\processors\extract-tags.js:54:17)
    at E:\dev\ideablade\angular.io\node_modules\dgeni-packages\jsdoc\processors\extract-tags.js:122:38
    at Function.forEach (E:\dev\ideablade\angular.io\node_modules\dgeni-packages\node_modules\lodash\dist\lodash.js:3298:15)
    at readTags (E:\dev\ideablade\angular.io\node_modules\dgeni-packages\jsdoc\processors\extract-tags.js:120:9)
    at E:\dev\ideablade\angular.io\node_modules\dgeni-packages\jsdoc\processors\extract-tags.js:86:11
    at Function.forEach (E:\dev\ideablade\angular.io\node_modules\dgeni-packages\node_modules\lodash\dist\lodash.js:3298:15)
    at tagExtractor (E:\dev\ideablade\angular.io\node_modules\dgeni-packages\jsdoc\processors\extract-tags.js:65:9)
    at E:\dev\ideablade\angular.io\node_modules\dgeni-packages\jsdoc\processors\extract-tags.js:20:9
    at Array.forEach (native)
[12:56:01] Finished '_shred-clean-api' after 3.63 s
[12:56:01] Finished '_shred-clean-devguide' after 3.65 s
zip created: public/resources/zips/styleguide.jsonly.zip (1921 total bytes)
zip created: public/resources/zips/styleguide.zip (3914 total bytes)
```

**Comment by filipesilva** [comment]
Fixed via https://github.com/angular/angular/pull/5827
