### ISSUE TITLE
Cannot read getXHR: errror executing (any) simple service test

### ISSUE THREAD

**Issue by Toadskin** [angular/angular.io#598]
TypeError: Cannot read property 'getXHR' of undefined 

Have not been able to get a service test to succeed yet as a result of this 

```typescript    
import {it, describe, expect, inject, beforeEachProviders} from 'angular2/testing'
import {MyService} from './my-service'
describe('sample test', () => {
    beforeEachProviders(() => [MyService])
    it('should work!', inject([MyService], (service:MyService) => {
          /* crashes */
    }))
})
```
Stack trace:

```
TypeError: Cannot read property 'getXHR' of undefined
    at _getAppBindings (http://127.0.0.1:8080/node_modules/angular2/bundles/testing.js:1830:1770)
    at Object.createTestInjector (http://127.0.0.1:8080/node_modules/angular2/bundles/testing.js:1837:79)
    at Object.<anonymous> (http://127.0.0.1:8080/node_modules/angular2/bundles/testing.js:1930:40)
    at attemptSync (http://127.0.0.1:8080/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1886:24)
    at QueueRunner.run (http://127.0.0.1:8080/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1874:9)
    at QueueRunner.execute (http://127.0.0.1:8080/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1859:10)
    at Spec.Env.queueRunnerFactory (http://127.0.0.1:8080/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:697:35)
    at Spec.execute (http://127.0.0.1:8080/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:359:10)
    at Object.fn (http://127.0.0.1:8080/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:2479:37)
    at attemptAsync (http://127.0.0.1:8080/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1916:24)
```

**Comment by ericmartinezr** [comment]
Check https://github.com/angular/angular/issues/6034

**Comment by Toadskin** [comment]
The resource reference in that #6034 link does not exist in the latest build.  I did manage to dig this up:

```typescript
import {BrowserDomAdapter} from 'angular2/src/core/dom/browser_adapter'
BrowserDomAdapter.makeCurrent() // in the test code
```
That fixes the getXHR errors, but leads to a trail of missing provider errors:
Http, ConnectionBackend, RequestOptions...

I was able to import them and fix the missing provider errors:

```
import {Http, ConnectionBackend, RequestOptions} from 'angular2/http'
```

But the test crashes with this:

```
Error: Cannot resolve all parameters for RequestOptions(?). Make sure they all have valid type or annotations.
```

**Comment by Toadskin** [comment]
No longer important as I just installed NG2 beta (was using alpha 50 something) and that broke pretty much everything. Going through and fixing up those errors and will circle back on this if it's still an issue with the new libraries.

**Comment by peder** [comment]
FYI, Toadskin, [this StackOverflow post](http://stackoverflow.com/questions/35055424/angular2-cannot-resolve-all-parameters-for-requestoptions) seems relevant. Rather than importing `Http`, `ConnectionBackend`, etc., simply import `HTTP_PROVIDERS`
